../../rtl/package/cv32e40p_pkg.sv
../../rtl/package/cv32e40p_fpu_pkg.sv
../../rtl/package/cv32e40p_apu_core_pkg.sv
../../rtl/cv32e40p_aligner.sv
../../rtl/cv32e40p_alu_div.sv
../../rtl/cv32e40p_alu.sv
../../rtl/cv32e40p_apu_disp.sv
../../rtl/cv32e40p_compressed_decoder.sv
../../rtl/cv32e40p_controller.sv
../../rtl/cv32e40p_core.sv
../../rtl/cv32e40p_cs_registers.sv
../../rtl/cv32e40p_decoder.sv
../../rtl/cv32e40p_ex_stage.sv
../../rtl/cv32e40p_ff_one.sv
../../rtl/cv32e40p_fifo.sv
../../rtl/cv32e40p_hwloop_regs.sv
../../rtl/cv32e40p_id_stage.sv
../../rtl/cv32e40p_if_stage.sv
../../rtl/cv32e40p_int_controller.sv
../../rtl/cv32e40p_load_store_unit.sv
../../rtl/cv32e40p_mult.sv
../../rtl/cv32e40p_obi_interface.sv
../../rtl/cv32e40p_popcnt.sv
../../rtl/cv32e40p_prefetch_buffer.sv
../../rtl/cv32e40p_prefetch_controller.sv
../../rtl/cv32e40p_register_file_ff.sv
../../rtl/cv32e40p_register_file_latch.sv
../../rtl/cv32e40p_sim_clock_gate.sv
../../rtl/cv32e40p_sleep_unit.sv
../../rtl/cv32e40p_top.sv
//===================================================
//interfaces
../lsu/lsu_if.sv
../ALU_DIV/tb_files/alu_if.sv
../mul/mul_interface.sv
../riscv_if.sv
../prefetch/fetch_if.sv
//===================================================
//packages
../riscv_pkg.sv
../riscv_classes_pkg.sv
//====================================================
../riscv_top_tb.sv
